### ISSUE TITLE
Conflict between Immersive Engeneering and Industrial Renewal mods.

### ISSUE THREAD

**Issue by Ostoff2** [Cassiobsk8/Industrial_Renewal#103]
**Versions:1.12.2**
-Minecraft Forge:14.23.5.2854
-Industrial Renewal:0.17.3 - 0.18.2

**What happens:The build doesn't start.**

**What should happen:The build should start.**

**Logs (if necessary)
[latest.log](https://github.com/Cassiobsk8/Industrial_Renewal/files/5440950/latest.log)
**

**Additional Comments:I created a build of + - 170 mods and there was a conflict between the Immersive Engineering and Industrial Renewal mods, I found out by disabling the Immersive Engineering mod.**

**Comment by Cassiobsk8** [comment]
Invalid id 4096 - maximum id range exceeded.
You need to add a mod to increase the number of IDs, I recommend https://www.curseforge.com/minecraft/mc-mods/notenoughids
this error has nothing to do with this mod, it is a limit of minecraft
