### ISSUE TITLE
Isolator for the UHV line that allows multiple connections to be made

### ISSUE THREAD

**Issue by RRyyas** [Cassiobsk8/Industrial_Renewal#120]
**Feature you want:**
Currently you can only connect a single line from one transformer to the other, and attempting to connect multiple lines to one isolator would return the message "Connection already in use", which makes it a problem when trying to create a power grid that goes from a single central power station with a transformer to multiple points with recieving transformers in each of the locations, because you can't split the power. That's why i'm requesting either that the isolator should be able to accept multiple connections or a special type of isolator where you can connect multiple lines to.

**Additional context:**
Immersive Engineering wires already supports this type of connection.

**Comment by Cassiobsk8** [comment]
This is intentional, if you need to divide the line you will need to set up a power distribution center (using transformers and energy cables)
