### ISSUE TITLE
Bunk bed spawn point broken

### ISSUE THREAD

**Issue by Hogan-Dazs** [Cassiobsk8/Industrial_Renewal#126]
**Versions:**
-Minecraft Forge: 14.23.5.2847
-Industrial Renewal: 0.21.6

**What happens:**
When the spawn point is set using a bunk other than the bottom most one, on respawn the message "Your home bed was missing or destroyed" is displayed and the default world spawn is used.

**What should happen:**
Any level of the bunk bed should correctly set the respawn point

**Comment by JustDesoroxxx** [comment]
The problem is related to how to bed in Minecraft work I have an idea of a workaround:

Take the bed find the nearest ground and then set spawn point here, it should work but I don't know how to do it
