### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jorgestudios** [Cassiobsk8/Industrial_Renewal#148]
**Versions:**
-Minecraft Forge: 14.23.5.2860
-Industrial Renewal: IndustrialRenewal_1.12.2-0.21.8

**What happens:**
it crashes 
**What should happen:**

**Logs (if necessary):**
https://paste.ofcode.org/3b86bwYEHuW8c3i2jtH4EQZ
**Additional Comments:**

**Comment by jorgestudios** [comment]
hello

**Comment by jorgestudios** [comment]
hello

**Comment by Desoroxxx** [comment]
This projects seems abandoned, I will consider maintaining this mod in the near future, currently busy working on multiple projects.

**Comment by jorgestudios** [comment]
ok thanks
