### ISSUE TITLE
Different colour caution blocks

### ISSUE THREAD

**Issue by crazytobuildmc** [Cassiobsk8/Industrial_Renewal#16]
**Feature you want:**
Multiple different colour combinations for the caution stripe blocks. IRL, there are many different ones aside from the famous yellow and black (physical hazard).

**Additional context:**
OSHA-specified barricade tape colors: (wikipedia woohoo)
Red / white for Fire Prevention and Protection Equipment.
Black / white for Housekeeping and Aisle Marking
Magenta / yellow for Radiation Hazards
Green / white for Safety and First Aid
Blue / white for Defective Machinery
Orange / white for Traffic and Caution Warning
Black / yellow for Physical Hazards

**Comment by Cassiobsk8** [comment]
https://imgur.com/a/rbdRZuT
