### ISSUE TITLE
Crash placing FuseBox Extension

### ISSUE THREAD

**Issue by wormzjl** [Cassiobsk8/Industrial_Renewal#22]
**Versions:**
-Minecraft Forge: 14.23.5.2768
-Industrial Renewal: IndustrialRenewal_1.12.2-0.7.0

**What happens:**
Placing fuse box on the ground

**Logs (if necessary):**
https://gist.github.com/wormzjl/451381ca98d907f3e55793f9b1af777a

**Additional Comments:**

**Comment by Cassiobsk8** [comment]
Sorry for the delay, i will fixes this now.
