### ISSUE TITLE
Weird issue when using industrial renewal stair in worldgen

### ISSUE THREAD

**Issue by wormzjl** [Cassiobsk8/Industrial_Renewal#29]
My issue is a bit weird. I've been trying to use industrial renewal block in world generation which looks like the follows:
![image](https://user-images.githubusercontent.com/2989009/53305021-79ad2000-387c-11e9-81c5-c504cfb43f30.png)

The problem is that, as you can see on the screenshot, all stairs pointing south (`industrialrenewal:catwalk_stair`) was instead pointing north (`industrialrenewal:catwalk_stair:2`). All other directions has no problems.

I've tried to specify the meta to be 0 in worldgen config, but it does not work. I guess it might be related to defaut blockstate?

So I wounder if there is anything that can be done on your side, thank you!

**Comment by Cassiobsk8** [comment]
industrialrenewal:catwalk_stair@0 is south and @2 is north I do not know what could be happening.
i spawn with command /setblock x y z industrialrenewal:catwalk_stair 0 and its point south
/setblock -448 3 1226 industrialrenewal:catwalk_stair 2 points to north
can you send me the command you are using?

**Comment by wormzjl** [comment]
Thank you for the reply, this is getting mysterious.
Actually I've been using Mcjty's lost cities for generation, will do some more investigation
