### ISSUE TITLE
Roller Shutter door?

### ISSUE THREAD

**Issue by Flithor** [Cassiobsk8/Industrial_Renewal#30]
Hope add Roller Shutter door.
And this:
![](https://media.discordapp.net/attachments/500443064989646852/558640570545733633/2019-03-22_21.16.58.png?width=400&height=225)
have some strange behavior. Maybe it maximum size is 2x2?

**Comment by Cassiobsk8** [comment]
The maximum is 2 in width, the height can be up to 3. For me to do bigger than that, I would have to implement multiblocks but I will not do it now because it lacks some blocks that I want to implement before.

**Comment by Flithor** [comment]
but if height is 3, model still strange
and if act that lowest block, only 2 highest door will change status

**Comment by Cassiobsk8** [comment]
I'll check, it should be a bug then
