### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by serialtasted** [Cassiobsk8/Industrial_Renewal#34]
It would be great to have more config options in the mod. To be able to tweak the mod into more what I want in my pack

Some config suggestions:

- In the "Electric Fence Damage Mode" would be nice to have a mode that doesn't do any damage (acting like normal vanilla fences) this would disable the warnings from the fences if possible

- Configurable knockback force (well if this added then the previous would be redundant because I could just set the damage amount to 0 and also set the knockback to 0)

- Alarm volume (distance in blocks which is heard)

- Barrel and Fluid cart capacity

- How many hearts the medkit restores

- Distance around the flame detector it can detect flames (it's the most useful thing to only detect flames right in front of it)

**Comment by Cassiobsk8** [comment]
Thanks for the suggestion, I will implement for the next version.
