### ISSUE TITLE
FPS lag during block updates

### ISSUE THREAD

**Issue by LemADEC** [Cassiobsk8/Industrial_Renewal#36]
**Versions:**
-Minecraft Forge: forge-14.23.5.2772
-Industrial Renewal: 1.12.2-0.9

**What happens:**
Whenever a block updates in the same chunk as IndustrialRenewal blocks, an FPS lag spike is observed. Lag increases as more IndustrialRenewal blocks are present in the area.

**What should happen:**
No FPS lag spike

**Logs (if necessary):**

**Additional Comments:**
This feels like the models or textures used by the mod aren't cached properly and get repeatedly computed for each block to render.

**Comment by Cassiobsk8** [comment]
I'll take a look at what might be happening.
