### ISSUE TITLE
[Question] What's the "Redstone Cartridges"?

### ISSUE THREAD

**Issue by Flithor** [Cassiobsk8/Industrial_Renewal#37]
I can't figure out the function of this item and related items.
Where are they used?
What realistic reference is it based on?
I don't know, so I can't translate its name at all.

**Comment by Cassiobsk8** [comment]
is used in the fuse box to manipulate the redstone output, it is based on these cartridges:
https://images.tcdn.com.br/img/img_prod/644524/88_0_20180801121412.jpg

**Comment by Flithor** [comment]
????
but in that picture are the fuse...
"cartridge“?????

**Comment by Cassiobsk8** [comment]
I'm just based on it, I'll send you some photos of their function

**Comment by Cassiobsk8** [comment]
![image](https://user-images.githubusercontent.com/2321158/58183430-b8892100-7c85-11e9-810c-d638b0fb89b0.png)

**Comment by Cassiobsk8** [comment]
look at redstone IN and redstone OUT and look at the cartridge, its two plus cartridge so its will get input and some with 2
the cartridge name may not be the best name for this item, if you have a better name I can use it.
