### ISSUE TITLE
Oversized textures

### ISSUE THREAD

**Issue by LemADEC** [Cassiobsk8/Industrial_Renewal#38]
**Versions:**
-Minecraft Forge: n/a
-Industrial Renewal: 1.12.2-0.9

**What happens:**
Some players are unable to load the mod due to lack of texture memory in their video card.
This is due to numerous oversized textures in the pack:
industrialrenewal:items/cargo_container
industrialrenewal:items/fluid_container
industrialrenewal:items/steam_locomotive
industrialrenewal:items/log_cart
industrialrenewal:items/passenger_car
Those 512x512 item textures are using as much space as 1024 items each.

**What should happen:**
Use a 3D model rendering of the item, or a lower resolution texture (16x16 is standard).

**Logs (if necessary):**
see the "Texture dump" mod for easy comparison with other mods.

**Additional Comments:**
Seen during Mischief of Mice stream of NatureCraft2 modpack.

**Comment by Cassiobsk8** [comment]
Thanks for reporting this. I would never guess that a very high texture for an item would give problems, I will try to solve it as soon as possible for the next release
