### ISSUE TITLE
Cargo Item Transfer Block - Doesn't release cart when cart is full

### ISSUE THREAD

**Issue by Kriegfox** [Cassiobsk8/Industrial_Renewal#40]
**Versions:**
-Minecraft Forge: 2768
-Industrial Renewal: 1.12.2-0.8.1

**What happens:**
Set the Cargo Item Transfer block to release cart when empty with a transfer rail above it. When the cart is empty, the cart is sent in the direction I set the transfer rail to. When it reaches the other end, I have the Cargo Item Transfer block to release cart when FULL, the cart fills all of its slot completely, full stacks of 64, with the transfer track setup the same way, but the cart never releases.

**What should happen:**
I would expect the Cargo Item Transfer block to release the cart when full if I have it set to do so.

**Logs (if necessary):**

**Additional Comments:**

**Comment by Cassiobsk8** [comment]
Fixed in Alpha1
