### ISSUE TITLE
IndustrialRenewal_1. 12.2 0.12.1. Jar    This can result in a large memory footprint

### ISSUE THREAD

**Issue by mcmso** [Cassiobsk8/Industrial_Renewal#41]
IndustrialRenewal_1. 12.2 0.12.1. Jar

This can result in a large memory footprint

**Comment by Cassiobsk8** [comment]
I do not understand what is causing the problem

**Comment by Franklin554** [comment]
Hello Cassiobsk8, 

the problem is that version 0.12.0 and 0.12.1 eat a lot more memory than previous versions. about 3-4 times as much

Greetz Frank

**Comment by GhEppIO82** [comment]
idem for me load minecraft take half an hour

**Comment by wormzjl** [comment]
Indeed, memory usage was increased about at least 1gb

**Comment by Cassiobsk8** [comment]
I'm trying to fix it, I already found the problem
