### ISSUE TITLE
Crash with fluid pipe

### ISSUE THREAD

**Issue by wormzjl** [Cassiobsk8/Industrial_Renewal#43]
Just messing fluid pipe and valve with some liquid tanks
Log: https://gist.github.com/wormzjl/48bddc6d8a3d26205f4f8361f515a058

**Comment by Cassiobsk8** [comment]
Can you send me a screenshot so I can reproduce here?

**Comment by wormzjl** [comment]
This does not seem to happen with a fixed setup, but randomly on block update.
I'm using magneticraft tank for testing, and I'm using openj9

**Comment by Cassiobsk8** [comment]
Ok thanks i will do some tests here

**Comment by wormzjl** [comment]
By the way I haven't figured out how to make pipes and valves work, can you give some hint about this?

**Comment by Cassiobsk8** [comment]
The valve can pull fluid from tanks and passes it only if it is open, pipes cannot pull fluid only send

**Comment by wormzjl** [comment]
Ok thanks! I thought that the value can be put in-line by the look of it.
