### ISSUE TITLE
HV Wires Render Bug

### ISSUE THREAD

**Issue by nalilord** [Cassiobsk8/Industrial_Renewal#72]
**Versions:**
-Minecraft Forge: 14.23.5.2847
-Industrial Renewal: 0.15.0

**What happens:**
After connecting HV Wires they get rendered wrong (screenshot) or have sections missing.

![javaw_vGMarK5lQe](https://user-images.githubusercontent.com/3942265/75801022-c3c3be00-5d7a-11ea-8286-42d763c34b2c.png)

**Comment by Cassiobsk8** [comment]
#59
