### ISSUE TITLE
Server Crash with Dam Generator

### ISSUE THREAD

**Issue by Rsslone** [Cassiobsk8/Industrial_Renewal#76]
**Versions:**
-Minecraft Forge: 1.12.2-14.23.5.2847
-Industrial Renewal: 16.1

**What happens:**
Server crashes on dam generator break
Unrelated to the crash I think but I can't seem to get the generator to output power. I have the turbine spinning. https://i.imgur.com/1hU1zh7.png

**Logs (if necessary):**
https://gist.github.com/Rsslone/94da5580d653559a204bbd2b377211ab
**Additional Comments:**

**Comment by Cassiobsk8** [comment]
Try to break the shaft and place again

**Comment by Rsslone** [comment]
I attempted to break both ends, and the whole thing. I spawned the items in creative if that matters.

**Comment by Rsslone** [comment]
Ah I think sponge and industrial renewal are not playing nice. I'll make a new issue for it.
