### ISSUE TITLE
Dam intake woefully underpowered; what am I doing wrong?

### ISSUE THREAD

**Issue by SodWhite** [Cassiobsk8/Industrial_Renewal#78]
I have built my turbine setup to spec as shown in the mod description and followed the intake tooltip's advice as closely as I could reckon based on what I was given, but the power per tick gained is minimal. I'm not sure how to get the most of out the turbine.

**Comment by Cassiobsk8** [comment]
Send a print of how you set it up.

**Comment by SodWhite** [comment]
User error. I re-checked the dimensions of the reservoir which were way too large, filled from the bottom, and the turbine kicked off to full chat. Resolved.
