### ISSUE TITLE
[Suggestion] [Rail] Cargo container & hoppers

### ISSUE THREAD

**Issue by slava110** [Cassiobsk8/Industrial_Renewal#9]
**Feature you want:**
We can't put items to cargo container with hopper. Can you add something that will put items in it? Or make cargo container work with hoppers?

**Additional context:**
![2018-08-17_14 54 31](https://user-images.githubusercontent.com/26705162/44264999-7978fb80-a22d-11e8-82a4-d4b0d26a89ba.png)

**Comment by Cassiobsk8** [comment]
the hopper needs to be one block down, and it's already working
