### ISSUE TITLE
Game crash because of electric pump

### ISSUE THREAD

**Issue by mattieboy079** [Cassiobsk8/Industrial_Renewal#90]
**Versions:**
-Minecraft Forge: 14.23.5.2854
-Industrial Renewal: 1.12.2-0.17.5

**What happens:**
Game crash

**What should happen:**
I guess the game shouldn't crash

**Logs (if necessary):**

**Additional Comments:**
I think it happens when the electric pump cannot pump his fluid to a destination.
It happened when I broke the boiler when the pump was running and pumping to the boiler.

**Comment by Cassiobsk8** [comment]
Post the Crash.log, without it I don't have much to do

**Comment by mattieboy079** [comment]
Sorry I was not on my computer the last few days, so I couldnt copy the crash report over here.
Is this what you are looking for?

[crash-2020-05-17_02.01.11-server.txt](https://github.com/Cassiobsk8/Industrial_Renewal/files/4649846/crash-2020-05-17_02.01.11-server.txt)

**Comment by Cassiobsk8** [comment]
Yes, thank you
