### ISSUE TITLE
Dam Intake is saying it's not a valid dam block

### ISSUE THREAD

**Issue by Captainaviator** [Cassiobsk8/Industrial_Renewal#97]
**Versions:**
-Minecraft Forge: 14.23.5.2847
-Industrial Renewal: 0.17.6

**What happens:**
Built a dam according to specs like in the video tutorial, except one intake is along a section of dam that's one block back from the other, but otherwise both dam segments have enough of their own concrete.
![2020-08-10_20 31 31](https://user-images.githubusercontent.com/24255062/89850038-792b4680-db4f-11ea-9af7-201aee77d301.png)
![2020-08-10_20 31 56](https://user-images.githubusercontent.com/24255062/89850060-834d4500-db4f-11ea-9d28-f28073d2078d.png)
![2020-08-10_20 32 47](https://user-images.githubusercontent.com/24255062/89850067-847e7200-db4f-11ea-8ea6-7e0d3101d531.png)

One intake is working at 100% efficiency, but the one that's one block back, says that it's own block is an invalid dam block.
Full message:
```
Efficiency: 76%
Concrete Amount: 110/143
Dam Intake at: X:-8765 Y: 52 Z:-6628 is not a valid dam block
```
and the coordinates read-out matches the block I clicked on

**What should happen:**
Both intakes should be operating at 100% efficiency

**Comment by Cassiobsk8** [comment]
There is gravel in the side
